config/routes.rb
Koyinsho::Application.routes.draw do
  root to:"housekeeping#home"

  match "/about" => "housekeeping#about", :as => :about
  match "/contact" => "housekeeping#contact", :as => :contact

  get "signout" => "sessions#destroy", as:"signout"
  get "signin" => "sessions#new", as:"signin"

  get "signup" => "members#new", as: "signup"

  resources :members
  resources :sessions
  
  get "/searches/contractors" => "searches#contractors"
  post "/searches/contractors" => "searches#contractors_post"

  resources :searches, :except => [:show] do
  end
  

end

app/views/layouts/application.html.haml
!!! 5
%html{lang:"en"}
  %head
    %title="Koyinsho | #{yield(:title)}"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <!--[if lt IE 9]>
    %script{src:"http://html5shim.googlecode.com/svn/trunk/html5.js"}
    <![endif]-->

  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        = link_to "Koyinsho", root_path, title:"Koyinsho.com (home)",class:"brand"
        .container
          %nav
            %ul.nav.pull-left
              %li.dropdown
                %a.dropdown-toggle{title:"Tutorials and other learning references.", 'data-toggle' => "dropdown", id:"mLabel1", role:"button", 'data-target' => "#"} Learn 
                %ul.dropdown-menu{role:"menu", 'aria-labelledby' => "mLabel1"}
                  %li= link_to "Amazon", '#', title:"Our Amazon Recommendations.", tabindex:"-1"
                  %li= link_to "Disqus", '#', title:"Our Property Management discussions.", tabindex:"-1"
              %li{class:"#{'active' if yield(:title) == "Search"}"}= link_to "Search", searches_path, title:"Find Business Trading Partners."
              %li{class:"#{'active' if yield(:title) == "Dashboard"}"}= link_to "Dashboard", "#", title:"View summarized decision-making data."
            %ul.nav.pull-right
              %li{class:"#{'active' if yield(:title) == "About"}"}= link_to "About", about_path, title:"All about Koyinsho services."
              %li{class:"#{'active' if yield(:title) == "Contact"}"}= link_to "Contact",contact_path, title:"Ask about concerns and give comments."
              %li.divider-vertical
              %li.dropdown
                %a.dropdown-toggle{title:"Manage your Koyinsho account.", 'data-toggle' => "dropdown", id:"mLabel9", role:"button", 'data-target' => "#"} Membership 
                %ul.dropdown-menu{role:"menu", 'aria-labelledby' => "mLabel9"}
                  - if !current_user
                    %li= link_to "Sign-in", signin_path, title:"Access your Koyinsho member benefits.", tabindex:"-1"
                    %li= link_to "Sign-up", signup_path, title:"Become a Koyinsho member.", tabindex:"-1"
                  - else
                    %li= link_to "Sign-out", signout_path, title:"Protect from unauthorized access.", tabindex:"-1"
                    %li= link_to "Account", '#', title:"Alter your Koyinsho membership.", tabindex:"-1"
    -flash.each do |name, msg|
      %div{class:"alert alert-#{name == :notice ? 'success' : 'error'}"}
        = msg
        %a.close{'data-dismiss' => 'alert'} &times;
    .container= yield
    = debug params